### ISSUE TITLE
trello plugin is not visible in sentry

### ISSUE THREAD

**Issue by shalakhin** [DamianZaremba/sentry-trello#19]
Using sentry 9.0.0 on own server with `sentry-plugins` and `sentry-trello` I don't see trello anywhere to enable. Is the plugin compatible with that version?

**Comment by RaSerge** [comment]
+1
We have Sentry 9.0
`sentry plugins list` shows 
`trello: sentry-trello 1.1.7 (/usr/local/lib/python2.7/site-packages)]`
but i also don't see trello in Integrations,

**Comment by comtihon** [comment]
I guess because of this:
```
Failed to load plugin 'trello':
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/sentry/runner/initializer.py", line 31, in register_plugins
    plugin = ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2324, in load
    self.require(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2347, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
ContextualVersionConflict: (redis 2.10.5 (/usr/local/lib/python2.7/site-packages), Requirement.parse('redis>=2.10.6'), set(['redis-py-cluster']))
```

**Comment by 0xhhhhh** [comment]
@comtihon I also encountered this problem.

**Comment by mhemrg** [comment]
This comment fixed the issue for me: https://github.com/getsentry/sentry-redmine/issues/16#issuecomment-430953076
